version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - npm i
artifacts:
  files:
    - '**/*'
  base-directory: ''
<<<<<<< HEAD

=======
 
>>>>>>> eb101dbfe61753fa9a44259db4d8d89d080c1f05
